// <auto-generated />
using DataContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_web_de_RESTful.Migrations
{
    [DbContext(typeof(BDContext))]
    partial class BDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ModelResidente.Residente.Residente", b =>
                {
                    b.Property<int>("Id_residente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_residente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Num_apartamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Num_telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_residente");

                    b.HasIndex("Id_User");

                    b.ToTable("Residentes");
                });

            modelBuilder.Entity("ModelsUser.User.User", b =>
                {
                    b.Property<int>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ModelResidente.Residente.Residente", b =>
                {
                    b.HasOne("ModelsUser.User.User", "usuario")
                        .WithMany()
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
